### ISSUE TITLE
ConvertFrom-Json : `Invalid JSON primitive: .`

### ISSUE THREAD

**Issue by Krutoy242** [NillerMedDild/ModpackUploader#16]
### Modpack Version

-

### Describe your issue.

I setup `settings.ps1` matching my pack options.
I skip all parts except actual uploading on CF.

When i lunch `modpack-uploader.ps1` i see this:

![Code_3qMrNWMwIv](https://user-images.githubusercontent.com/936618/167260212-7efa74bc-6425-45a5-a7d6-0f2cda133b01.gif)

Seems like something wrong with CF output.
Error:
```less
ConvertFrom-Json : Недопустимый примитив JSON: .
D:\mc_client\Instances\Enigmatica2Expert - Extended\modpackUploader\modpack-uploader.ps1:245 знак:30       
+             --progress-bar | ConvertFrom-Json
+                              ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
 
Failed to upload client files: 
Failed to upload client files: 
D:\mc_client\Instances\Enigmatica2Expert - Extended\modpackUploader\modpack-uploader.ps1:252 знак:13
+             throw "Failed to upload client files: $response"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to upload client files: :String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to upload client files: 
```

I tried to redirect output of `curl.exe` in file:
```diff
- --progress-bar | ConvertFrom-Json
+ > out.html
```

Opening `out.html` i see this:

![image](https://user-images.githubusercontent.com/936618/167260341-6356a5d0-c632-4148-a6bc-9519cb60f978.png)

Why this happen? How to fix that?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report. Could you please provide your `settings.ps1` file? Also, I take it you've added your api token to the `secrets.ps1` file?

**Comment by IronworksProductions** [comment]
I am also getting the same error, API token is added. my setttings.ps1 is here: https://gist.github.com/MetaverseRPN/de37892b5eefcc4981cda3f229c58cfc


<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/MetaverseRPN/de37892b5eefcc4981cda3f229c58cfc">gist:de37892b5eefcc4981cda3f229c58cfc</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by NielsPilgaard** [comment]
Any chance you have a the returned error in english? 😅

**Comment by IronworksProductions** [comment]
I do. Here it is:
```
Failed to upload client files: @{errorCode=1002; errorMessage=Error in field `metadata`:
Invalid JSON.}
Failed to upload client files: @{errorCode=1002; errorMessage=Error in field `metadata`:
Invalid JSON.}
At C:\Users\nicho\curseforge\minecraft\Instances\Protocol Beta test\modpack-uploader.ps1:250 char:13
+             throw "Failed to upload client files: $response"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to uploa...
Invalid JSON.}:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to upload client files: @{errorCode=1002; errorMessage=Error in field `metadata`:

Invalid JSON.}
```
_Edit: only took 5 tries to get that codeblocked correctly_

**Comment by NielsPilgaard** [comment]
Thank you kindly. Do you also have the output just prior to this? I'm looking for something like this:

```
Client Metadata:

{
            changelog: 'The Changelog is currently being written, it should be done soon.',
            changelogType: 'markdown',
            displayName: 'Enigmatica 6 1.2.1',
            gameVersions: [8203],
            releaseType: 'alpha'
        }

**Comment by IronworksProductions** [comment]
```
Client Metadata:

{
            changelog: 'You aren't supposed to be here... There is nothing for you to see here...',
            changelogType: 'markdown',
            displayName: 'PhoenixRising 0.0.1',
            gameVersions: [6756],
            releaseType: 'beta'
        }
```
Is this what you are looking for?

**Comment by NielsPilgaard** [comment]
It is indeed. Odd, that looks perfectly valid. 
I'm guessing they're finally patching the odd json format they used to expect. Could you perhaps re-try a couple of times, see if you reach one of their API servers that haven't updated yet? 😄 I was able to use this a few minutes ago.

**Comment by IronworksProductions** [comment]
Im trying for the 3rd time but it seems I am getting this error every time I try

**Comment by Krutoy242** [comment]
Yes, i tried different time a day and same error.

**Comment by NielsPilgaard** [comment]
Hmm alright. Could you please try replacing the setting of the `$CLIENT_METADATA` parameter like below?

Change this:
```ps1
$CLIENT_METADATA = 
        "{
            changelog: `'$CLIENT_CHANGELOG`',
            changelogType: `'$CLIENT_CHANGELOG_TYPE`',
            displayName: `'$CLIENT_FILE_DISPLAY_NAME`',
            gameVersions: [$GAME_VERSIONS],
            releaseType: `'$CLIENT_RELEASE_TYPE`'
        }"
```
to this:
```ps1
$CLIENT_METADATA = @{
    changelog     = $CLIENT_CHANGELOG
    changelogType = $CLIENT_CHANGELOG_TYPE
    displayName   = $CLIENT_FILE_DISPLAY_NAME
    gameVersions  = $GAME_VERSIONS
    releaseType   = $CLIENT_RELEASE_TYPE
} | ConvertTo-Json

**Comment by IronworksProductions** [comment]
Trying it now

**Comment by IronworksProductions** [comment]
um.... Ok this is a new one.....
```
curl: (6) Could not resolve host: aren\u0027t

curl: (6) Could not resolve host: supposed

curl: (6) Could not resolve host: to

curl: (6) Could not resolve host: be

curl: (6) Could not resolve host: here...

curl: (6) Could not resolve host: There

curl: (6) Could not resolve host: is

curl: (6) Could not resolve host: nothing

curl: (6) Could not resolve host: for

curl: (6) Could not resolve host: you

curl: (6) Could not resolve host: to

curl: (6) Could not resolve host: see

curl: (3) bad range specification in URL position 31:
here...,
    gameVersions:  [
                         6756
                     ],
    changelogType:  markdown,
    releaseType:  beta,
    displayName:  PhoenixRising
```

**Comment by NielsPilgaard** [comment]
Yikes. CurseForge still dislikes normal JSON I guess :P

Please revert that change, and make this change instead:

Change:
```ps1
-F metadata=$CLIENT_METADATA
```

to
```ps1
-F metadata=([System.Text.Encoding]::UTF8.GetBytes($CLIENT_METADATA ))
```

**Comment by Krutoy242** [comment]
> `-F metadata=([System.Text.Encoding]::UTF8.GetBytes($CLIENT_METADATA ))`

I tried this. After uploading progress bar, slowly got similar messages `curl: (6) Could not resolve host: 32` again and again:

```sh
######################################################################## 100,0%

curl: (6) Could not resolve host: 123

curl: (6) Could not resolve host: 13

curl: (6) Could not resolve host: 10

curl: (6) Could not resolve host: 32

curl: (6) Could not resolve host: 32

curl: (6) Could not resolve host: 32

curl: (6) Could not resolve host: 32

curl: (6) Could not resolve host: 32
```

**Comment by NielsPilgaard** [comment]
Oh woops, I think it should've been:
`-F metadata=([System.Text.Encoding]::UTF8.GetString($CLIENT_METADATA))`

**Comment by Krutoy242** [comment]
```less
The argument "bytes" cannot be converted, with the value: "{
            changelog: 'The Changelog is currently being written, please ignore.',
            changelogType: 'markdown',
            displayName: 'E2E-Extended v0.56.0',
            gameVersions: [6756],
            releaseType: 'beta'
        }", for "GetString" into type "System.Byte[]": "Cannot convert value "{
            changelog: 'The Changelog is currently being written, please ignore.',
            changelogType: 'markdown',
            displayName: 'E2E-Extended v0.56.0',
            gameVersions: [6756],
            releaseType: 'beta'
        }" в тип "System.Byte[]". Error: "Cannot convert value "{
            changelog: 'The Changelog is currently being written, please ignore.',
            changelogType: 'markdown',
            displayName: 'E2E-Extended v0.56.0',
            gameVersions: [6756],
            releaseType: 'beta'
        }" в тип "System.Byte". Ошибка: "The input string was in the wrong format."""
D:\mc_client\Instances\Enigmatica2Expert - Extended\modpackUploader\modpack-uploader.ps1:238 знак:9
+         $response = curl.exe `
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument
 
Failed to upload client files: 
Failed to upload client files: 
D:\mc_client\Instances\Enigmatica2Expert - Extended\modpackUploader\modpack-uploader.ps1:252 знак:13
+             throw "Failed to upload client files: $response"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to upload client files: :String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to upload client files: 
```
